From brett at python.org  Wed May  1 15:26:28 2019
From: brett at python.org (Brett Cannon)
Date: Wed, 1 May 2019 15:26:28 -0400
Subject: [python-committers] Vote on changes to PEP 13 to specify voting
 time frames
In-Reply-To: <CAP1=2W4yvn8iPEJFd1kTGk_pzT4QS4mko4iSmUc6EXTc7wOnLA@mail.gmail.com>
References: <CAP1=2W4yvn8iPEJFd1kTGk_pzT4QS4mko4iSmUc6EXTc7wOnLA@mail.gmail.com>
Message-ID: <CAP1=2W7kALkM2+aBpi1R=PG7rcVnjPXhQQQUvHHyfJzwTc1xcA@mail.gmail.com>

The vote has closed and the ayes have it with 85% of the vote. Thanks to
everyone who participated!

On Wed, Apr 17, 2019 at 1:01 PM Brett Cannon <brett at python.org> wrote:

>
> https://discuss.python.org/t/vote-on-pep-13-change-to-specify-voting-time-frames/1510
>
> Summary: one week to vote for new core devs, two weeks for PEP 13 changes
> (which is how long I set the vote on Discourse to be open for). This change
> is approved by the steering council.
>
> And as a reminder, changes to PEP 13 require a 2/3 approval by voters.
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190501/b562225b/attachment.html>

From guido at python.org  Wed May  1 15:56:46 2019
From: guido at python.org (Guido van Rossum)
Date: Wed, 1 May 2019 15:56:46 -0400
Subject: [python-committers] Vote on changes to PEP 13 to specify voting
 time frames
In-Reply-To: <CAP1=2W7kALkM2+aBpi1R=PG7rcVnjPXhQQQUvHHyfJzwTc1xcA@mail.gmail.com>
References: <CAP1=2W4yvn8iPEJFd1kTGk_pzT4QS4mko4iSmUc6EXTc7wOnLA@mail.gmail.com>
 <CAP1=2W7kALkM2+aBpi1R=PG7rcVnjPXhQQQUvHHyfJzwTc1xcA@mail.gmail.com>
Message-ID: <CAP7+vJLkLq5VmSQc2PmX=3cL2tVWBc+r=jd8=zk2Cq-p6Bst4Q@mail.gmail.com>

Thanks!

On Wed, May 1, 2019 at 15:26 Brett Cannon <brett at python.org> wrote:

> The vote has closed and the ayes have it with 85% of the vote. Thanks to
> everyone who participated!
>
> On Wed, Apr 17, 2019 at 1:01 PM Brett Cannon <brett at python.org> wrote:
>
>>
>> https://discuss.python.org/t/vote-on-pep-13-change-to-specify-voting-time-frames/1510
>>
>> Summary: one week to vote for new core devs, two weeks for PEP 13 changes
>> (which is how long I set the vote on Discourse to be open for). This change
>> is approved by the steering council.
>>
>> And as a reminder, changes to PEP 13 require a 2/3 approval by voters.
>>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-- 
--Guido (mobile)
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190501/e23512b9/attachment.html>

From cheryl.sabella at gmail.com  Mon May  6 13:33:38 2019
From: cheryl.sabella at gmail.com (Cheryl Sabella)
Date: Mon, 6 May 2019 13:33:38 -0400
Subject: [python-committers] Anthony Shaw has been given the bug triage
 permission
Message-ID: <CABcGAgC9hpjv-B5PUgsUJ72ag5Ts4b7tNyK6wvd_qCRDEgk_Hg@mail.gmail.com>

Hello,

During the PyCon sprints, I mentored Anthony Shaw (from Real Python) on
triaging bug issues and GitHub pull requests.  I will continue to mentor
him, but to help him have the greatest impact, he has been given the triage
bit.

Congratulations Anthony!


Cheryl Sabella
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190506/067b7448/attachment.html>

From steve.dower at python.org  Mon May  6 13:49:53 2019
From: steve.dower at python.org (Steve Dower)
Date: Mon, 6 May 2019 13:49:53 -0400
Subject: [python-committers] Anthony Shaw has been given the bug triage
 permission
In-Reply-To: <CABcGAgC9hpjv-B5PUgsUJ72ag5Ts4b7tNyK6wvd_qCRDEgk_Hg@mail.gmail.com>
References: <CABcGAgC9hpjv-B5PUgsUJ72ag5Ts4b7tNyK6wvd_qCRDEgk_Hg@mail.gmail.com>
Message-ID: <adb6ce41-9a79-b273-58dc-50a1a2bfd88c@python.org>

On 06May2019 1333, Cheryl Sabella wrote:
> Hello,
> 
> During the PyCon sprints, I mentored Anthony Shaw (from Real Python) on 
> triaging bug issues and GitHub pull requests.? I will continue to mentor 
> him, but to help him have the greatest impact, he has been given the 
> triage bit.
> 
> Congratulations Anthony!

Congratulations! Great to have you on board!

Cheers,
Steve


From willingc at gmail.com  Mon May  6 15:52:19 2019
From: willingc at gmail.com (Carol Willing)
Date: Mon, 6 May 2019 15:52:19 -0400
Subject: [python-committers] Anthony Shaw has been given the bug triage
 permission
In-Reply-To: <adb6ce41-9a79-b273-58dc-50a1a2bfd88c@python.org>
References: <CABcGAgC9hpjv-B5PUgsUJ72ag5Ts4b7tNyK6wvd_qCRDEgk_Hg@mail.gmail.com>
 <adb6ce41-9a79-b273-58dc-50a1a2bfd88c@python.org>
Message-ID: <07fc7d1f-9c8b-d09f-fb48-98920734c952@gmail.com>

Fantastic! Congrats Anthony :D

Steve Dower wrote on 5/6/19 1:49 PM:
> On 06May2019 1333, Cheryl Sabella wrote:
>> Hello,
>>
>> During the PyCon sprints, I mentored Anthony Shaw (from Real Python) 
>> on triaging bug issues and GitHub pull requests.? I will continue to 
>> mentor him, but to help him have the greatest impact, he has been 
>> given the triage bit.
>>
>> Congratulations Anthony!
>
> Congratulations! Great to have you on board!
>
> Cheers,
> Steve
>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/


From lukasz at langa.pl  Tue May  7 10:58:27 2019
From: lukasz at langa.pl (=?utf-8?Q?=C5=81ukasz_Langa?=)
Date: Tue, 7 May 2019 10:58:27 -0400
Subject: [python-committers] [RELEASE] Python 3.8.0a4 is now available for
 testing
Message-ID: <27210321-6B27-4629-9643-2A64F62DA85D@langa.pl>

It's time for the LAST alpha of Python 3.8.0. Go get it here:
https://www.python.org/downloads/release/python-380a4/ <https://www.python.org/downloads/release/python-380a4/>

Python 3.8.0a4 is the fourth and final alpha release of Python 3.8,
the next feature release of Python.  During the alpha phase, Python 3.8
remains under heavy development: additional features will be added
and existing features may be modified or deleted.  Please keep in mind
that this is a preview release and its use is not recommended for
production environments.  The first beta release, 3.8.0b1, is planned
for 2019-05-31.

The release has slipped a week because of me being overwhelmed
with PyCon US this year.  There was also a release blocker and
a breaking change to ElementTree.  Anyway, sorry for the wait!
I moved the planned date of beta1 a few days to make up for it.

If you have a feature you're working on and you'd like to see it in
3.8.0, NOW IS THE TIME TO ACT. Please don't wait until May 30th,
get a proper review and land your change as soon as possible.

Q: Can I get my feature in after that date if I ask nicely?
A: Yes, of course. I will release it in Python 3.9.

- ?
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190507/048f5414/attachment.html>
-------------- next part --------------
A non-text attachment was scrubbed...
Name: signature.asc
Type: application/pgp-signature
Size: 833 bytes
Desc: Message signed with OpenPGP
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190507/048f5414/attachment.sig>

From antoine at python.org  Wed May  8 11:32:13 2019
From: antoine at python.org (Antoine Pitrou)
Date: Wed, 8 May 2019 17:32:13 +0200
Subject: [python-committers] Merge with spurious CI failures?
Message-ID: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>


Hello,

There are spurious CI failures (SSL certificate issue in test_httplib).
Therefore the "Squash and merge" button is greyed out.

How should I merge? Using the command-line instructions from Github?

Regards

Antoine.

From larry at hastings.org  Wed May  8 11:36:45 2019
From: larry at hastings.org (Larry Hastings)
Date: Wed, 8 May 2019 11:36:45 -0400
Subject: [python-committers] Farewell, Python 3.4
Message-ID: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>


It's with a note of sadness that I announce the final retirement of 
Python 3.4.? The final release was back in March, but I didn't get 
around to actually closing and deleting the 3.4 branch until this morning.

Python 3.4 introduced many features we all enjoy in modern Python--the 
asyncio, ensurepip, and enum packages, just to name three.? It's a 
release I hope we all remember fondly.

My eternal thanks to all the members of the release team that worked on 
Python 3.4:

    Georg Brandl

    Julien Palard

    Martin von L?wis

    Ned Deily

    Steve Dower

    Terry Reedy

    and all the engineers of the Python infrastructure team.

Special thanks to Benjamin Peterson and Ned Deily, who frequently 
scurried around behind the scenes cleaning up the messes I cluelessly 
left in my wake.

Having closed 3.4, I am now retired as Python 3.4 Release Manager.? I 
regret to inform all of you that you're still stuck with me as Python 
3.5 Release Manager until sometime next year.


My very best wishes,


//arry/

-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/cc7e10bc/attachment.html>

From alex.gaynor at gmail.com  Wed May  8 11:37:02 2019
From: alex.gaynor at gmail.com (Alex Gaynor)
Date: Wed, 8 May 2019 11:37:02 -0400
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
Message-ID: <CAFRnB2Waaa=6Mo768JokH7Stn0=H1WWNkgcH08sf=cHD2djd3A@mail.gmail.com>

Are these intermittent failures, or is there bustage on master right now?

My usual habit on other projects (I'm not very active on CPython these
days) is to restart the build on travis so that is a nice green checkmark.

Alex

On Wed, May 8, 2019 at 11:32 AM Antoine Pitrou <antoine at python.org> wrote:

>
> Hello,
>
> There are spurious CI failures (SSL certificate issue in test_httplib).
> Therefore the "Squash and merge" button is greyed out.
>
> How should I merge? Using the command-line instructions from Github?
>
> Regards
>
> Antoine.
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>


-- 
All that is necessary for evil to succeed is for good people to do nothing.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/8965b209/attachment.html>

From antoine at python.org  Wed May  8 11:44:02 2019
From: antoine at python.org (Antoine Pitrou)
Date: Wed, 8 May 2019 17:44:02 +0200
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <CAFRnB2Waaa=6Mo768JokH7Stn0=H1WWNkgcH08sf=cHD2djd3A@mail.gmail.com>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAFRnB2Waaa=6Mo768JokH7Stn0=H1WWNkgcH08sf=cHD2djd3A@mail.gmail.com>
Message-ID: <7244393f-b1db-014c-78f3-ba7dbd00637b@python.org>


They're deterministic.  Apparently the test which connects to
"self-signed.pythontest.net" always fails now with a "self-signed
certificate" error...

Le 08/05/2019 ? 17:37, Alex Gaynor a ?crit?:
> Are these intermittent failures, or is there bustage on master right now?
> 
> My usual habit on other projects (I'm not very active on CPython these
> days) is to restart the build on travis so that is a nice green checkmark.
> 
> Alex
> 
> On Wed, May 8, 2019 at 11:32 AM Antoine Pitrou <antoine at python.org
> <mailto:antoine at python.org>> wrote:
> 
> 
>     Hello,
> 
>     There are spurious CI failures (SSL certificate issue in test_httplib).
>     Therefore the "Squash and merge" button is greyed out.
> 
>     How should I merge? Using the command-line instructions from Github?
> 
>     Regards
> 
>     Antoine.
>     _______________________________________________
>     python-committers mailing list
>     python-committers at python.org <mailto:python-committers at python.org>
>     https://mail.python.org/mailman/listinfo/python-committers
>     Code of Conduct: https://www.python.org/psf/codeofconduct/
> 
> 
> 
> -- 
> All that is necessary for evil to succeed is for good people to do nothing.

From alex.gaynor at gmail.com  Wed May  8 11:45:46 2019
From: alex.gaynor at gmail.com (Alex Gaynor)
Date: Wed, 8 May 2019 11:45:46 -0400
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <7244393f-b1db-014c-78f3-ba7dbd00637b@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAFRnB2Waaa=6Mo768JokH7Stn0=H1WWNkgcH08sf=cHD2djd3A@mail.gmail.com>
 <7244393f-b1db-014c-78f3-ba7dbd00637b@python.org>
Message-ID: <CAFRnB2XZYKJjsnZoM5icyrRds-1dsski0B2FSsGcdRdgBBz9JQ@mail.gmail.com>

I don't know if CPython has a specific policy about this -- other projects
I work on generally have a "we need to get master's tests passing again
before anything can merge" policy.

Alex

On Wed, May 8, 2019 at 11:44 AM Antoine Pitrou <antoine at python.org> wrote:

>
> They're deterministic.  Apparently the test which connects to
> "self-signed.pythontest.net" always fails now with a "self-signed
> certificate" error...
>
> Le 08/05/2019 ? 17:37, Alex Gaynor a ?crit :
> > Are these intermittent failures, or is there bustage on master right now?
> >
> > My usual habit on other projects (I'm not very active on CPython these
> > days) is to restart the build on travis so that is a nice green
> checkmark.
> >
> > Alex
> >
> > On Wed, May 8, 2019 at 11:32 AM Antoine Pitrou <antoine at python.org
> > <mailto:antoine at python.org>> wrote:
> >
> >
> >     Hello,
> >
> >     There are spurious CI failures (SSL certificate issue in
> test_httplib).
> >     Therefore the "Squash and merge" button is greyed out.
> >
> >     How should I merge? Using the command-line instructions from Github?
> >
> >     Regards
> >
> >     Antoine.
> >     _______________________________________________
> >     python-committers mailing list
> >     python-committers at python.org <mailto:python-committers at python.org>
> >     https://mail.python.org/mailman/listinfo/python-committers
> >     Code of Conduct: https://www.python.org/psf/codeofconduct/
> >
> >
> >
> > --
> > All that is necessary for evil to succeed is for good people to do
> nothing.
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>


-- 
All that is necessary for evil to succeed is for good people to do nothing.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/40cfab99/attachment.html>

From mal at egenix.com  Wed May  8 11:46:05 2019
From: mal at egenix.com (M.-A. Lemburg)
Date: Wed, 8 May 2019 17:46:05 +0200
Subject: [python-committers] [Python-Dev] Farewell, Python 3.4
In-Reply-To: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>
References: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>
Message-ID: <efb89d1b-47a2-8ca2-49b8-241be2231453@egenix.com>

Thank you for having been 3.4 release manager, Larry !

On 08.05.2019 17:36, Larry Hastings wrote:
> 
> It's with a note of sadness that I announce the final retirement of
> Python 3.4.? The final release was back in March, but I didn't get
> around to actually closing and deleting the 3.4 branch until this morning.
> 
> Python 3.4 introduced many features we all enjoy in modern Python--the
> asyncio, ensurepip, and enum packages, just to name three.? It's a
> release I hope we all remember fondly.
> 
> My eternal thanks to all the members of the release team that worked on
> Python 3.4:
> 
>     Georg Brandl
> 
>     Julien Palard
> 
>     Martin von L?wis
> 
>     Ned Deily
> 
>     Steve Dower
> 
>     Terry Reedy
> 
>     and all the engineers of the Python infrastructure team.
> 
> Special thanks to Benjamin Peterson and Ned Deily, who frequently
> scurried around behind the scenes cleaning up the messes I cluelessly
> left in my wake.
> 
> Having closed 3.4, I am now retired as Python 3.4 Release Manager.? I
> regret to inform all of you that you're still stuck with me as Python
> 3.5 Release Manager until sometime next year.
> 
> 
> My very best wishes,
> 
> 
> //arry/
> 
> 
> 
> _______________________________________________
> Python-Dev mailing list
> Python-Dev at python.org
> https://mail.python.org/mailman/listinfo/python-dev
> Unsubscribe: https://mail.python.org/mailman/options/python-dev/mal%40egenix.com
> 

-- 
Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Experts (#1, May 08 2019)
>>> Python Projects, Coaching and Consulting ...  http://www.egenix.com/
>>> Python Database Interfaces ...           http://products.egenix.com/
>>> Plone/Zope Database Interfaces ...           http://zope.egenix.com/
________________________________________________________________________

::: We implement business ideas - efficiently in both time and costs :::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               http://www.egenix.com/company/contact/
                      http://www.malemburg.com/


From mariatta at python.org  Wed May  8 11:49:47 2019
From: mariatta at python.org (Mariatta)
Date: Wed, 8 May 2019 08:49:47 -0700
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
Message-ID: <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>

If you can't merge from GitHub UI then you won't be able to do it from
GitHub command line (it respects the same branch protection policy)

I don't think we should merge if tests are still failing. Perhaps the test
should be adjusted to handle this spurious errors? Can it be marked as
"allowed failure" or something like that?


On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org> wrote:

>
> Hello,
>
> There are spurious CI failures (SSL certificate issue in test_httplib).
> Therefore the "Squash and merge" button is greyed out.
>
> How should I merge? Using the command-line instructions from Github?
>
> Regards
>
> Antoine.
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/cf6195b4/attachment.html>

From eric at trueblade.com  Wed May  8 11:51:13 2019
From: eric at trueblade.com (Eric V. Smith)
Date: Wed, 8 May 2019 11:51:13 -0400
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
Message-ID: <495F990B-14E6-49FC-9C6A-1B72CD3F8684@trueblade.com>

Surely there must be some way around it. After all, how would you merge a PR to fix this test?

--
Eric V. Smith
True Blade Systems, Inc
(301) 859-4544

> On May 8, 2019, at 11:49 AM, Mariatta <mariatta at python.org> wrote:
> 
> If you can't merge from GitHub UI then you won't be able to do it from GitHub command line (it respects the same branch protection policy)
> 
> I don't think we should merge if tests are still failing. Perhaps the test should be adjusted to handle this spurious errors? Can it be marked as "allowed failure" or something like that?
> 
> 
>> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org> wrote:
>> 
>> Hello,
>> 
>> There are spurious CI failures (SSL certificate issue in test_httplib).
>> Therefore the "Squash and merge" button is greyed out.
>> 
>> How should I merge? Using the command-line instructions from Github?
>> 
>> Regards
>> 
>> Antoine.
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/dfd47daf/attachment-0001.html>

From alex.gaynor at gmail.com  Wed May  8 11:52:00 2019
From: alex.gaynor at gmail.com (Alex Gaynor)
Date: Wed, 8 May 2019 11:52:00 -0400
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <495F990B-14E6-49FC-9C6A-1B72CD3F8684@trueblade.com>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <495F990B-14E6-49FC-9C6A-1B72CD3F8684@trueblade.com>
Message-ID: <CAFRnB2WoRPKOXC4iNryQY5Qeogu0KbcvQmCj=2tvAfkGPotpnA@mail.gmail.com>

Tests for that PR would presumably be green :-)

Alex

On Wed, May 8, 2019 at 11:51 AM Eric V. Smith <eric at trueblade.com> wrote:

> Surely there must be some way around it. After all, how would you merge a
> PR to fix this test?
>
> --
> Eric V. Smith
> True Blade Systems, Inc
> (301) 859-4544
>
> On May 8, 2019, at 11:49 AM, Mariatta <mariatta at python.org> wrote:
>
> If you can't merge from GitHub UI then you won't be able to do it from
> GitHub command line (it respects the same branch protection policy)
>
> I don't think we should merge if tests are still failing. Perhaps the test
> should be adjusted to handle this spurious errors? Can it be marked as
> "allowed failure" or something like that?
>
>
> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org> wrote:
>
>>
>> Hello,
>>
>> There are spurious CI failures (SSL certificate issue in test_httplib).
>> Therefore the "Squash and merge" button is greyed out.
>>
>> How should I merge? Using the command-line instructions from Github?
>>
>> Regards
>>
>> Antoine.
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>


-- 
All that is necessary for evil to succeed is for good people to do nothing.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/989bccc7/attachment.html>

From eric at trueblade.com  Wed May  8 11:54:06 2019
From: eric at trueblade.com (Eric V. Smith)
Date: Wed, 8 May 2019 11:54:06 -0400
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <CAFRnB2WoRPKOXC4iNryQY5Qeogu0KbcvQmCj=2tvAfkGPotpnA@mail.gmail.com>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <495F990B-14E6-49FC-9C6A-1B72CD3F8684@trueblade.com>
 <CAFRnB2WoRPKOXC4iNryQY5Qeogu0KbcvQmCj=2tvAfkGPotpnA@mail.gmail.com>
Message-ID: <12B09861-7FC2-4412-81E8-73BC7191F25A@trueblade.com>

D?oh! Good point!

Eric

> On May 8, 2019, at 11:52 AM, Alex Gaynor <alex.gaynor at gmail.com> wrote:
> 
> Tests for that PR would presumably be green :-)
> 
> Alex
> 
>> On Wed, May 8, 2019 at 11:51 AM Eric V. Smith <eric at trueblade.com> wrote:
>> Surely there must be some way around it. After all, how would you merge a PR to fix this test?
>> 
>> --
>> Eric V. Smith
>> True Blade Systems, Inc
>> (301) 859-4544
>> 
>>> On May 8, 2019, at 11:49 AM, Mariatta <mariatta at python.org> wrote:
>>> 
>>> If you can't merge from GitHub UI then you won't be able to do it from GitHub command line (it respects the same branch protection policy)
>>> 
>>> I don't think we should merge if tests are still failing. Perhaps the test should be adjusted to handle this spurious errors? Can it be marked as "allowed failure" or something like that?
>>> 
>>> 
>>>> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org> wrote:
>>>> 
>>>> Hello,
>>>> 
>>>> There are spurious CI failures (SSL certificate issue in test_httplib).
>>>> Therefore the "Squash and merge" button is greyed out.
>>>> 
>>>> How should I merge? Using the command-line instructions from Github?
>>>> 
>>>> Regards
>>>> 
>>>> Antoine.
>>>> _______________________________________________
>>>> python-committers mailing list
>>>> python-committers at python.org
>>>> https://mail.python.org/mailman/listinfo/python-committers
>>>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>> _______________________________________________
>>> python-committers mailing list
>>> python-committers at python.org
>>> https://mail.python.org/mailman/listinfo/python-committers
>>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
> 
> 
> -- 
> All that is necessary for evil to succeed is for good people to do nothing.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/500f2981/attachment.html>

From antoine at python.org  Wed May  8 11:58:37 2019
From: antoine at python.org (Antoine Pitrou)
Date: Wed, 8 May 2019 17:58:37 +0200
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
Message-ID: <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>


Ok, apparently the SSL cert on self-signed.pythontest.net was changed
but it wasn't updated in our source tree, hence the failure.

Regards

Antoine.


Le 08/05/2019 ? 17:49, Mariatta a ?crit?:
> If you can't merge from GitHub UI then you won't be able to do it from
> GitHub command line (it respects the same branch protection policy)
> 
> I don't think we should merge if tests are still failing. Perhaps the
> test should be adjusted to handle this spurious errors? Can it be marked
> as "allowed failure" or something like that?
> 
> 
> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org
> <mailto:antoine at python.org>> wrote:
> 
> 
>     Hello,
> 
>     There are spurious CI failures (SSL certificate issue in test_httplib).
>     Therefore the "Squash and merge" button is greyed out.
> 
>     How should I merge? Using the command-line instructions from Github?
> 
>     Regards
> 
>     Antoine.
>     _______________________________________________
>     python-committers mailing list
>     python-committers at python.org <mailto:python-committers at python.org>
>     https://mail.python.org/mailman/listinfo/python-committers
>     Code of Conduct: https://www.python.org/psf/codeofconduct/
> 

From alex.gaynor at gmail.com  Wed May  8 12:00:22 2019
From: alex.gaynor at gmail.com (Alex Gaynor)
Date: Wed, 8 May 2019 12:00:22 -0400
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
Message-ID: <CAFRnB2W-bvXDx530NrNqMnUs08x_8pQaXbwkrDx9tLMy2i2Xiw@mail.gmail.com>

https://github.com/python/cpython/pull/13192

Thanks gps!

Alex

On Wed, May 8, 2019 at 11:58 AM Antoine Pitrou <antoine at python.org> wrote:

>
> Ok, apparently the SSL cert on self-signed.pythontest.net was changed
> but it wasn't updated in our source tree, hence the failure.
>
> Regards
>
> Antoine.
>
>
> Le 08/05/2019 ? 17:49, Mariatta a ?crit :
> > If you can't merge from GitHub UI then you won't be able to do it from
> > GitHub command line (it respects the same branch protection policy)
> >
> > I don't think we should merge if tests are still failing. Perhaps the
> > test should be adjusted to handle this spurious errors? Can it be marked
> > as "allowed failure" or something like that?
> >
> >
> > On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org
> > <mailto:antoine at python.org>> wrote:
> >
> >
> >     Hello,
> >
> >     There are spurious CI failures (SSL certificate issue in
> test_httplib).
> >     Therefore the "Squash and merge" button is greyed out.
> >
> >     How should I merge? Using the command-line instructions from Github?
> >
> >     Regards
> >
> >     Antoine.
> >     _______________________________________________
> >     python-committers mailing list
> >     python-committers at python.org <mailto:python-committers at python.org>
> >     https://mail.python.org/mailman/listinfo/python-committers
> >     Code of Conduct: https://www.python.org/psf/codeofconduct/
> >
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>


-- 
All that is necessary for evil to succeed is for good people to do nothing.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/668c7ae7/attachment.html>

From antoine at python.org  Wed May  8 12:00:51 2019
From: antoine at python.org (Antoine Pitrou)
Date: Wed, 8 May 2019 18:00:51 +0200
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
Message-ID: <446fdea8-bc33-c698-e840-7f6831b60378@python.org>


Ah, there's already a PR at
https://github.com/python/cpython/pull/13192, thanks to Gregory.

Regards

Antoine.


Le 08/05/2019 ? 17:58, Antoine Pitrou a ?crit?:
> 
> Ok, apparently the SSL cert on self-signed.pythontest.net was changed
> but it wasn't updated in our source tree, hence the failure.
> 
> Regards
> 
> Antoine.
> 
> 
> Le 08/05/2019 ? 17:49, Mariatta a ?crit?:
>> If you can't merge from GitHub UI then you won't be able to do it from
>> GitHub command line (it respects the same branch protection policy)
>>
>> I don't think we should merge if tests are still failing. Perhaps the
>> test should be adjusted to handle this spurious errors? Can it be marked
>> as "allowed failure" or something like that?
>>
>>
>> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org
>> <mailto:antoine at python.org>> wrote:
>>
>>
>>     Hello,
>>
>>     There are spurious CI failures (SSL certificate issue in test_httplib).
>>     Therefore the "Squash and merge" button is greyed out.
>>
>>     How should I merge? Using the command-line instructions from Github?
>>
>>     Regards
>>
>>     Antoine.
>>     _______________________________________________
>>     python-committers mailing list
>>     python-committers at python.org <mailto:python-committers at python.org>
>>     https://mail.python.org/mailman/listinfo/python-committers
>>     Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
> 

From greg at krypto.org  Wed May  8 12:04:54 2019
From: greg at krypto.org (Gregory P. Smith)
Date: Wed, 8 May 2019 11:04:54 -0500
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
Message-ID: <CAGE7PNKOyBVJYj3mpBK6eFpWDqeAeS03vnVwEwwMi55gTFnncw@mail.gmail.com>

Our pythontestdotnet repo is different than the cpython repo and the
certificate gets pushed to the server after being committed by hand so it's
a synchronization problem,.

https://github.com/python/cpython/pull/13192 should clear it up.  It's
awaiting the slow CI queuing gods.  It is marked automerge, so if a core
dev could go do a github review and Approve it, it'll go in immediately
after Travis and AppVeyor come back green.

-gps

On Wed, May 8, 2019 at 10:58 AM Antoine Pitrou <antoine at python.org> wrote:

>
> Ok, apparently the SSL cert on self-signed.pythontest.net was changed
> but it wasn't updated in our source tree, hence the failure.
>
> Regards
>
> Antoine.
>
>
> Le 08/05/2019 ? 17:49, Mariatta a ?crit :
> > If you can't merge from GitHub UI then you won't be able to do it from
> > GitHub command line (it respects the same branch protection policy)
> >
> > I don't think we should merge if tests are still failing. Perhaps the
> > test should be adjusted to handle this spurious errors? Can it be marked
> > as "allowed failure" or something like that?
> >
> >
> > On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org
> > <mailto:antoine at python.org>> wrote:
> >
> >
> >     Hello,
> >
> >     There are spurious CI failures (SSL certificate issue in
> test_httplib).
> >     Therefore the "Squash and merge" button is greyed out.
> >
> >     How should I merge? Using the command-line instructions from Github?
> >
> >     Regards
> >
> >     Antoine.
> >     _______________________________________________
> >     python-committers mailing list
> >     python-committers at python.org <mailto:python-committers at python.org>
> >     https://mail.python.org/mailman/listinfo/python-committers
> >     Code of Conduct: https://www.python.org/psf/codeofconduct/
> >
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/1c192866/attachment-0001.html>

From greg at krypto.org  Wed May  8 12:15:05 2019
From: greg at krypto.org (Gregory P. Smith)
Date: Wed, 8 May 2019 11:15:05 -0500
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <446fdea8-bc33-c698-e840-7f6831b60378@python.org>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
 <446fdea8-bc33-c698-e840-7f6831b60378@python.org>
Message-ID: <CAGE7PNJoD9USPnQMucLo8pQApVBQQ9jVZfDSEP5Rdsds_3UMbg@mail.gmail.com>

If this cert change is impacting CI checks for everyone's PRs, I suspect
all PRs will need to merge this change into their branch before they can
pass CI.

Having CI depend on external network resources does not seem like a good
idea.

-gps

On Wed, May 8, 2019 at 11:04 AM Antoine Pitrou <antoine at python.org> wrote:

>
> Ah, there's already a PR at
> https://github.com/python/cpython/pull/13192, thanks to Gregory.
>
> Regards
>
> Antoine.
>
>
> Le 08/05/2019 ? 17:58, Antoine Pitrou a ?crit :
> >
> > Ok, apparently the SSL cert on self-signed.pythontest.net was changed
> > but it wasn't updated in our source tree, hence the failure.
> >
> > Regards
> >
> > Antoine.
> >
> >
> > Le 08/05/2019 ? 17:49, Mariatta a ?crit :
> >> If you can't merge from GitHub UI then you won't be able to do it from
> >> GitHub command line (it respects the same branch protection policy)
> >>
> >> I don't think we should merge if tests are still failing. Perhaps the
> >> test should be adjusted to handle this spurious errors? Can it be marked
> >> as "allowed failure" or something like that?
> >>
> >>
> >> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org
> >> <mailto:antoine at python.org>> wrote:
> >>
> >>
> >>     Hello,
> >>
> >>     There are spurious CI failures (SSL certificate issue in
> test_httplib).
> >>     Therefore the "Squash and merge" button is greyed out.
> >>
> >>     How should I merge? Using the command-line instructions from Github?
> >>
> >>     Regards
> >>
> >>     Antoine.
> >>     _______________________________________________
> >>     python-committers mailing list
> >>     python-committers at python.org <mailto:python-committers at python.org>
> >>     https://mail.python.org/mailman/listinfo/python-committers
> >>     Code of Conduct: https://www.python.org/psf/codeofconduct/
> >>
> > _______________________________________________
> > python-committers mailing list
> > python-committers at python.org
> > https://mail.python.org/mailman/listinfo/python-committers
> > Code of Conduct: https://www.python.org/psf/codeofconduct/
> >
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/5e93b8de/attachment.html>

From greg at krypto.org  Wed May  8 12:44:00 2019
From: greg at krypto.org (Gregory P. Smith)
Date: Wed, 8 May 2019 11:44:00 -0500
Subject: [python-committers] miss-islington backport pipeline is stalled?
Message-ID: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>

Yesterday it failed to produce a backport or tell me that it couldn't
(after the "i'm now working on ..." message was left on the master PR).  I
waited a couple hours just in case and ran cherry_picker myself instead.
Same thing today apparently on
https://github.com/python/cpython/pull/13192 assuming
the usual backport latency is no more than a minute or two.

-gps
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/f39bd053/attachment.html>

From mariatta at python.org  Wed May  8 13:02:37 2019
From: mariatta at python.org (Mariatta)
Date: Wed, 8 May 2019 10:02:37 -0700
Subject: [python-committers] miss-islington backport pipeline is stalled?
In-Reply-To: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>
References: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>
Message-ID: <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>

There was an error from Redis. I think this is the first time I've seen it,
so I don't have any resolution on how to fix it right now.  ?
I will look into handling the error and have miss-islington leave a comment
in the PR when there is such error.

log:

at=info method=POST path="/" host=miss-islington.herokuapp.com
request_id=8de611a2-6112-4039-a425-97850ac989b0 fwd="140.82.115.15"
dyno=web.1 connect=1ms service=1005ms status=200 bytes=168
protocol=https
May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py",
line 600, in send_packed_command
May 08 09:35:15 miss-islington app/web.1:     self._sock.sendall(item)
May 08 09:35:15 miss-islington app/web.1: TimeoutError: [Errno 110]
Connection timed out
May 08 09:35:15 miss-islington app/web.1: During handling of the above
exception, another exception occurred:
May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py",
line 431, in _reraise_as_library_errors
May 08 09:35:15 miss-islington app/web.1:     yield
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/celery/app/base.py",
line 744, in send_task
May 08 09:35:15 miss-islington app/web.1:
self.backend.on_task_call(P, task_id)
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py",
line 265, in on_task_call
May 08 09:35:15 miss-islington app/web.1:
self.result_consumer.consume_from(task_id)
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py",
line 126, in consume_from
May 08 09:35:15 miss-islington app/web.1:     self._consume_from(task_id)
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py",
line 132, in _consume_from
May 08 09:35:15 miss-islington app/web.1:     self._pubsub.subscribe(key)
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py",
line 3096, in subscribe
May 08 09:35:15 miss-islington app/web.1:     ret_val =
self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py",
line 3009, in execute_command
May 08 09:35:15 miss-islington app/web.1:
self._execute(connection, connection.send_command, *args)
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/redis/client.py",
line 3013, in _execute
May 08 09:35:15 miss-islington app/web.1:     return command(*args)
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py",
line 620, in send_command
May 08 09:35:15 miss-islington app/web.1:
self.send_packed_command(self.pack_command(*args))
May 08 09:35:15 miss-islington app/web.1:   File
"/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py",
line 613, in send_packed_command
May 08 09:35:15 miss-islington app/web.1:     (errno, errmsg))
May 08 09:35:15 miss-islington app/web.1:
redis.exceptions.ConnectionError: Error 110 while writing to socket.
Connection timed out.



?

On Wed, May 8, 2019 at 9:44 AM Gregory P. Smith <greg at krypto.org> wrote:

> Yesterday it failed to produce a backport or tell me that it couldn't
> (after the "i'm now working on ..." message was left on the master PR).  I
> waited a couple hours just in case and ran cherry_picker myself instead.
> Same thing today apparently on
> https://github.com/python/cpython/pull/13192 assuming the usual backport
> latency is no more than a minute or two.
>
> -gps
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/136eadbe/attachment-0001.html>

From alex.gaynor at gmail.com  Wed May  8 13:04:01 2019
From: alex.gaynor at gmail.com (Alex Gaynor)
Date: Wed, 8 May 2019 13:04:01 -0400
Subject: [python-committers] miss-islington backport pipeline is stalled?
In-Reply-To: <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>
References: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>
 <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>
Message-ID: <CAFRnB2X-m7T2_Dy2ZaaByvb0TKekOD+ZKLjYUJkQ==YvfKpaJg@mail.gmail.com>

Would it make sense to work with the PSF infra staff so that
miss-isslington is hooked up to the PSF Sentry account so folks can get
email notifications and similar on unhandled exceptions?

Alex

On Wed, May 8, 2019 at 1:02 PM Mariatta <mariatta at python.org> wrote:

> There was an error from Redis. I think this is the first time I've seen
> it, so I don't have any resolution on how to fix it right now.  ?
> I will look into handling the error and have miss-islington leave a
> comment in the PR when there is such error.
>
> log:
>
> at=info method=POST path="/" host=miss-islington.herokuapp.com request_id=8de611a2-6112-4039-a425-97850ac989b0 fwd="140.82.115.15" dyno=web.1 connect=1ms service=1005ms status=200 bytes=168 protocol=https
> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 600, in send_packed_command
> May 08 09:35:15 miss-islington app/web.1:     self._sock.sendall(item)
> May 08 09:35:15 miss-islington app/web.1: TimeoutError: [Errno 110] Connection timed out
> May 08 09:35:15 miss-islington app/web.1: During handling of the above exception, another exception occurred:
> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
> May 08 09:35:15 miss-islington app/web.1:     yield
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/base.py", line 744, in send_task
> May 08 09:35:15 miss-islington app/web.1:     self.backend.on_task_call(P, task_id)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 265, in on_task_call
> May 08 09:35:15 miss-islington app/web.1:     self.result_consumer.consume_from(task_id)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 126, in consume_from
> May 08 09:35:15 miss-islington app/web.1:     self._consume_from(task_id)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 132, in _consume_from
> May 08 09:35:15 miss-islington app/web.1:     self._pubsub.subscribe(key)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3096, in subscribe
> May 08 09:35:15 miss-islington app/web.1:     ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3009, in execute_command
> May 08 09:35:15 miss-islington app/web.1:     self._execute(connection, connection.send_command, *args)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
> May 08 09:35:15 miss-islington app/web.1:     return command(*args)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
> May 08 09:35:15 miss-islington app/web.1:     self.send_packed_command(self.pack_command(*args))
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 613, in send_packed_command
> May 08 09:35:15 miss-islington app/web.1:     (errno, errmsg))
> May 08 09:35:15 miss-islington app/web.1: redis.exceptions.ConnectionError: Error 110 while writing to socket. Connection timed out.
>
>
>
> ?
>
> On Wed, May 8, 2019 at 9:44 AM Gregory P. Smith <greg at krypto.org> wrote:
>
>> Yesterday it failed to produce a backport or tell me that it couldn't
>> (after the "i'm now working on ..." message was left on the master PR).  I
>> waited a couple hours just in case and ran cherry_picker myself instead.
>> Same thing today apparently on
>> https://github.com/python/cpython/pull/13192 assuming the usual backport
>> latency is no more than a minute or two.
>>
>> -gps
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>


-- 
All that is necessary for evil to succeed is for good people to do nothing.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/d0eb7b61/attachment.html>

From greg at krypto.org  Wed May  8 13:06:53 2019
From: greg at krypto.org (Gregory P. Smith)
Date: Wed, 8 May 2019 12:06:53 -0500
Subject: [python-committers] Merge with spurious CI failures?
In-Reply-To: <CAGE7PNJoD9USPnQMucLo8pQApVBQQ9jVZfDSEP5Rdsds_3UMbg@mail.gmail.com>
References: <97679bdc-a199-bc1e-2951-7c30fba47803@python.org>
 <CAGbohnaYQof_RmAMAM3O9uUfxaWxQVeKS3==BKwot_ZcRcCfbA@mail.gmail.com>
 <9283dcda-b847-2eda-a79a-c6ffa02d03d9@python.org>
 <446fdea8-bc33-c698-e840-7f6831b60378@python.org>
 <CAGE7PNJoD9USPnQMucLo8pQApVBQQ9jVZfDSEP5Rdsds_3UMbg@mail.gmail.com>
Message-ID: <CAGE7PNL7GQK4GHZUyFWP5JmX9rGUOjqgA65i1G5=M5bTkmoa-w@mail.gmail.com>

fwiw a future way to avoid this mess is in
https://bugs.python.org/issue36855: have the tests support multiple
certificates so we can stage the new ones into our repo before updating the
server.

-gps

On Wed, May 8, 2019 at 11:15 AM Gregory P. Smith <greg at krypto.org> wrote:

> If this cert change is impacting CI checks for everyone's PRs, I suspect
> all PRs will need to merge this change into their branch before they can
> pass CI.
>
> Having CI depend on external network resources does not seem like a good
> idea.
>
> -gps
>
> On Wed, May 8, 2019 at 11:04 AM Antoine Pitrou <antoine at python.org> wrote:
>
>>
>> Ah, there's already a PR at
>> https://github.com/python/cpython/pull/13192, thanks to Gregory.
>>
>> Regards
>>
>> Antoine.
>>
>>
>> Le 08/05/2019 ? 17:58, Antoine Pitrou a ?crit :
>> >
>> > Ok, apparently the SSL cert on self-signed.pythontest.net was changed
>> > but it wasn't updated in our source tree, hence the failure.
>> >
>> > Regards
>> >
>> > Antoine.
>> >
>> >
>> > Le 08/05/2019 ? 17:49, Mariatta a ?crit :
>> >> If you can't merge from GitHub UI then you won't be able to do it from
>> >> GitHub command line (it respects the same branch protection policy)
>> >>
>> >> I don't think we should merge if tests are still failing. Perhaps the
>> >> test should be adjusted to handle this spurious errors? Can it be
>> marked
>> >> as "allowed failure" or something like that?
>> >>
>> >>
>> >> On Wed, May 8, 2019, 8:32 AM Antoine Pitrou <antoine at python.org
>> >> <mailto:antoine at python.org>> wrote:
>> >>
>> >>
>> >>     Hello,
>> >>
>> >>     There are spurious CI failures (SSL certificate issue in
>> test_httplib).
>> >>     Therefore the "Squash and merge" button is greyed out.
>> >>
>> >>     How should I merge? Using the command-line instructions from
>> Github?
>> >>
>> >>     Regards
>> >>
>> >>     Antoine.
>> >>     _______________________________________________
>> >>     python-committers mailing list
>> >>     python-committers at python.org <mailto:python-committers at python.org>
>> >>     https://mail.python.org/mailman/listinfo/python-committers
>> >>     Code of Conduct: https://www.python.org/psf/codeofconduct/
>> >>
>> > _______________________________________________
>> > python-committers mailing list
>> > python-committers at python.org
>> > https://mail.python.org/mailman/listinfo/python-committers
>> > Code of Conduct: https://www.python.org/psf/codeofconduct/
>> >
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/4e0e8e36/attachment-0001.html>

From mariatta at python.org  Wed May  8 13:09:38 2019
From: mariatta at python.org (Mariatta)
Date: Wed, 8 May 2019 10:09:38 -0700
Subject: [python-committers] miss-islington backport pipeline is stalled?
In-Reply-To: <CAFRnB2X-m7T2_Dy2ZaaByvb0TKekOD+ZKLjYUJkQ==YvfKpaJg@mail.gmail.com>
References: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>
 <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>
 <CAFRnB2X-m7T2_Dy2ZaaByvb0TKekOD+ZKLjYUJkQ==YvfKpaJg@mail.gmail.com>
Message-ID: <CAGbohnY6DSqocYvdiesa0wAqj2JtJr8YObC_JGBpXjrc1rwcGg@mail.gmail.com>

We don't have sentry (I will ask Ernest about it), but such errors are
already sent to Zulip (
https://python.zulipchat.com/#narrow/stream/142203-workflow.2Fbot-api.20rate.20limit/topic/alerts/near/165174773)
and core-workflow
https://github.com/python/core-workflow/issues/257#issuecomment-490541831
But posting back to the PR itself will still be useful.
?

On Wed, May 8, 2019 at 10:04 AM Alex Gaynor <alex.gaynor at gmail.com> wrote:

> Would it make sense to work with the PSF infra staff so that
> miss-isslington is hooked up to the PSF Sentry account so folks can get
> email notifications and similar on unhandled exceptions?
>
> Alex
>
> On Wed, May 8, 2019 at 1:02 PM Mariatta <mariatta at python.org> wrote:
>
>> There was an error from Redis. I think this is the first time I've seen
>> it, so I don't have any resolution on how to fix it right now.  ?
>> I will look into handling the error and have miss-islington leave a
>> comment in the PR when there is such error.
>>
>> log:
>>
>> at=info method=POST path="/" host=miss-islington.herokuapp.com request_id=8de611a2-6112-4039-a425-97850ac989b0 fwd="140.82.115.15" dyno=web.1 connect=1ms service=1005ms status=200 bytes=168 protocol=https
>> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 600, in send_packed_command
>> May 08 09:35:15 miss-islington app/web.1:     self._sock.sendall(item)
>> May 08 09:35:15 miss-islington app/web.1: TimeoutError: [Errno 110] Connection timed out
>> May 08 09:35:15 miss-islington app/web.1: During handling of the above exception, another exception occurred:
>> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
>> May 08 09:35:15 miss-islington app/web.1:     yield
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/base.py", line 744, in send_task
>> May 08 09:35:15 miss-islington app/web.1:     self.backend.on_task_call(P, task_id)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 265, in on_task_call
>> May 08 09:35:15 miss-islington app/web.1:     self.result_consumer.consume_from(task_id)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 126, in consume_from
>> May 08 09:35:15 miss-islington app/web.1:     self._consume_from(task_id)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 132, in _consume_from
>> May 08 09:35:15 miss-islington app/web.1:     self._pubsub.subscribe(key)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3096, in subscribe
>> May 08 09:35:15 miss-islington app/web.1:     ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3009, in execute_command
>> May 08 09:35:15 miss-islington app/web.1:     self._execute(connection, connection.send_command, *args)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
>> May 08 09:35:15 miss-islington app/web.1:     return command(*args)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
>> May 08 09:35:15 miss-islington app/web.1:     self.send_packed_command(self.pack_command(*args))
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 613, in send_packed_command
>> May 08 09:35:15 miss-islington app/web.1:     (errno, errmsg))
>> May 08 09:35:15 miss-islington app/web.1: redis.exceptions.ConnectionError: Error 110 while writing to socket. Connection timed out.
>>
>>
>>
>> ?
>>
>> On Wed, May 8, 2019 at 9:44 AM Gregory P. Smith <greg at krypto.org> wrote:
>>
>>> Yesterday it failed to produce a backport or tell me that it couldn't
>>> (after the "i'm now working on ..." message was left on the master PR).  I
>>> waited a couple hours just in case and ran cherry_picker myself instead.
>>> Same thing today apparently on
>>> https://github.com/python/cpython/pull/13192 assuming the usual
>>> backport latency is no more than a minute or two.
>>>
>>> -gps
>>> _______________________________________________
>>> python-committers mailing list
>>> python-committers at python.org
>>> https://mail.python.org/mailman/listinfo/python-committers
>>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>>
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
>
>
> --
> All that is necessary for evil to succeed is for good people to do nothing.
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/f39b3f89/attachment.html>

From brett at python.org  Wed May  8 13:10:05 2019
From: brett at python.org (Brett Cannon)
Date: Wed, 8 May 2019 13:10:05 -0400
Subject: [python-committers] miss-islington backport pipeline is stalled?
In-Reply-To: <CAFRnB2X-m7T2_Dy2ZaaByvb0TKekOD+ZKLjYUJkQ==YvfKpaJg@mail.gmail.com>
References: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>
 <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>
 <CAFRnB2X-m7T2_Dy2ZaaByvb0TKekOD+ZKLjYUJkQ==YvfKpaJg@mail.gmail.com>
Message-ID: <CAP1=2W7FPq6MmbFbGbHp8OG+6j256_a_Z4sMdY0ToLhfLgHH-A@mail.gmail.com>

On Wed, May 8, 2019 at 1:04 PM Alex Gaynor <alex.gaynor at gmail.com> wrote:

> Would it make sense to work with the PSF infra staff so that
> miss-isslington is hooked up to the PSF Sentry account so folks can get
> email notifications and similar on unhandled exceptions?
>

Yes it would. :)

-Brett


>
> Alex
>
> On Wed, May 8, 2019 at 1:02 PM Mariatta <mariatta at python.org> wrote:
>
>> There was an error from Redis. I think this is the first time I've seen
>> it, so I don't have any resolution on how to fix it right now.  ?
>> I will look into handling the error and have miss-islington leave a
>> comment in the PR when there is such error.
>>
>> log:
>>
>> at=info method=POST path="/" host=miss-islington.herokuapp.com request_id=8de611a2-6112-4039-a425-97850ac989b0 fwd="140.82.115.15" dyno=web.1 connect=1ms service=1005ms status=200 bytes=168 protocol=https
>> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 600, in send_packed_command
>> May 08 09:35:15 miss-islington app/web.1:     self._sock.sendall(item)
>> May 08 09:35:15 miss-islington app/web.1: TimeoutError: [Errno 110] Connection timed out
>> May 08 09:35:15 miss-islington app/web.1: During handling of the above exception, another exception occurred:
>> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
>> May 08 09:35:15 miss-islington app/web.1:     yield
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/base.py", line 744, in send_task
>> May 08 09:35:15 miss-islington app/web.1:     self.backend.on_task_call(P, task_id)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 265, in on_task_call
>> May 08 09:35:15 miss-islington app/web.1:     self.result_consumer.consume_from(task_id)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 126, in consume_from
>> May 08 09:35:15 miss-islington app/web.1:     self._consume_from(task_id)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 132, in _consume_from
>> May 08 09:35:15 miss-islington app/web.1:     self._pubsub.subscribe(key)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3096, in subscribe
>> May 08 09:35:15 miss-islington app/web.1:     ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3009, in execute_command
>> May 08 09:35:15 miss-islington app/web.1:     self._execute(connection, connection.send_command, *args)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
>> May 08 09:35:15 miss-islington app/web.1:     return command(*args)
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
>> May 08 09:35:15 miss-islington app/web.1:     self.send_packed_command(self.pack_command(*args))
>> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 613, in send_packed_command
>> May 08 09:35:15 miss-islington app/web.1:     (errno, errmsg))
>> May 08 09:35:15 miss-islington app/web.1: redis.exceptions.ConnectionError: Error 110 while writing to socket. Connection timed out.
>>
>>
>>
>> ?
>>
>> On Wed, May 8, 2019 at 9:44 AM Gregory P. Smith <greg at krypto.org> wrote:
>>
>>> Yesterday it failed to produce a backport or tell me that it couldn't
>>> (after the "i'm now working on ..." message was left on the master PR).  I
>>> waited a couple hours just in case and ran cherry_picker myself instead.
>>> Same thing today apparently on
>>> https://github.com/python/cpython/pull/13192 assuming the usual
>>> backport latency is no more than a minute or two.
>>>
>>> -gps
>>> _______________________________________________
>>> python-committers mailing list
>>> python-committers at python.org
>>> https://mail.python.org/mailman/listinfo/python-committers
>>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>>
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
>
>
> --
> All that is necessary for evil to succeed is for good people to do nothing.
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190508/a46b491e/attachment-0001.html>

From tjreedy at udel.edu  Wed May  8 14:56:40 2019
From: tjreedy at udel.edu (Terry Reedy)
Date: Wed, 8 May 2019 14:56:40 -0400
Subject: [python-committers] [Python-Dev] Farewell, Python 3.4
In-Reply-To: <efb89d1b-47a2-8ca2-49b8-241be2231453@egenix.com>
References: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>
 <efb89d1b-47a2-8ca2-49b8-241be2231453@egenix.com>
Message-ID: <12e725f4-ee6f-1a9a-e02b-c8d527fe29ea@udel.edu>

On 5/8/2019 11:46 AM, M.-A. Lemburg wrote:
> Thank you for having been 3.4 release manager, Larry !

I especially appreciate being able to have proper signatures for builtin 
functions.


From benjamin at python.org  Wed May  8 22:23:17 2019
From: benjamin at python.org (Benjamin Peterson)
Date: Wed, 08 May 2019 22:23:17 -0400
Subject: [python-committers] [Python-Dev] Farewell, Python 3.4
In-Reply-To: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>
References: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>
Message-ID: <7bca5961-b8cd-42d8-8a00-1384e31de010@www.fastmail.com>

Thank you for your service!

On Wed, May 8, 2019, at 08:37, Larry Hastings wrote:
> 
> 
> It's with a note of sadness that I announce the final retirement of 
> Python 3.4. The final release was back in March, but I didn't get 
> around to actually closing and deleting the 3.4 branch until this 
> morning.
> 
> Python 3.4 introduced many features we all enjoy in modern Python--the 
> asyncio, ensurepip, and enum packages, just to name three. It's a 
> release I hope we all remember fondly.
> 
> My eternal thanks to all the members of the release team that worked on 
> Python 3.4:
> 
> > Georg Brandl
> 
> > Julien Palard
> 
> > Martin von L?wis
> 
> > Ned Deily
> 
> > Steve Dower
> 
> > Terry Reedy
> 
> > and all the engineers of the Python infrastructure team.
> 
> Special thanks to Benjamin Peterson and Ned Deily, who frequently 
> scurried around behind the scenes cleaning up the messes I cluelessly 
> left in my wake.
> 
> Having closed 3.4, I am now retired as Python 3.4 Release Manager. I 
> regret to inform all of you that you're still stuck with me as Python 
> 3.5 Release Manager until sometime next year.
> 
> 
> 
> My very best wishes,
> 
> 
> 
> */arry*
> 
> _______________________________________________
> Python-Dev mailing list
> Python-Dev at python.org
> https://mail.python.org/mailman/listinfo/python-dev
> Unsubscribe: 
> https://mail.python.org/mailman/options/python-dev/benjamin%40python.org
>

From antoine at python.org  Thu May  9 04:11:09 2019
From: antoine at python.org (Antoine Pitrou)
Date: Thu, 9 May 2019 10:11:09 +0200
Subject: [python-committers] [Python-Dev] Farewell, Python 3.4
In-Reply-To: <7bca5961-b8cd-42d8-8a00-1384e31de010@www.fastmail.com>
References: <f8034796-9f54-c779-7697-83a86e583a13@hastings.org>
 <7bca5961-b8cd-42d8-8a00-1384e31de010@www.fastmail.com>
Message-ID: <bec018ee-3d5d-aaa5-e34c-19d1409276e5@python.org>


Thank you for being a generally reasonable being.

Regards

Antoine.


Le 09/05/2019 ? 04:23, Benjamin Peterson a ?crit?:
> Thank you for your service!
> 
> On Wed, May 8, 2019, at 08:37, Larry Hastings wrote:
>>
>>
>> It's with a note of sadness that I announce the final retirement of 
>> Python 3.4. The final release was back in March, but I didn't get 
>> around to actually closing and deleting the 3.4 branch until this 
>> morning.
>>
>> Python 3.4 introduced many features we all enjoy in modern Python--the 
>> asyncio, ensurepip, and enum packages, just to name three. It's a 
>> release I hope we all remember fondly.
>>
>> My eternal thanks to all the members of the release team that worked on 
>> Python 3.4:
>>
>>> Georg Brandl
>>
>>> Julien Palard
>>
>>> Martin von L?wis
>>
>>> Ned Deily
>>
>>> Steve Dower
>>
>>> Terry Reedy
>>
>>> and all the engineers of the Python infrastructure team.
>>
>> Special thanks to Benjamin Peterson and Ned Deily, who frequently 
>> scurried around behind the scenes cleaning up the messes I cluelessly 
>> left in my wake.
>>
>> Having closed 3.4, I am now retired as Python 3.4 Release Manager. I 
>> regret to inform all of you that you're still stuck with me as Python 
>> 3.5 Release Manager until sometime next year.
>>
>>
>>
>> My very best wishes,
>>
>>
>>
>> */arry*
>>
>> _______________________________________________
>> Python-Dev mailing list
>> Python-Dev at python.org
>> https://mail.python.org/mailman/listinfo/python-dev
>> Unsubscribe: 
>> https://mail.python.org/mailman/options/python-dev/benjamin%40python.org
>>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
> 

From mariatta at python.org  Thu May  9 12:03:51 2019
From: mariatta at python.org (Mariatta)
Date: Thu, 9 May 2019 09:03:51 -0700
Subject: [python-committers] miss-islington backport pipeline is stalled?
In-Reply-To: <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>
References: <CAGE7PNK8T=BCZa7iEDx+eDrEh8w+_4hgD6U96RqjRkP7BaAcsg@mail.gmail.com>
 <CAGbohnZRxXqdLU1Cn7RrTNym1Z5-K1xt+XKPDcC-auzDR2J2_g@mail.gmail.com>
Message-ID: <CAGbohnY0cuqfr3TXme2o13H_z-O6GqseBrLToEpaM9anFqtsjg@mail.gmail.com>

I'm seeing more of this today, just heads up in case you see miss-islington
not working.

Seems like this is a known issue with celery + kombu ?
https://github.com/celery/kombu/issues/1019
?

On Wed, May 8, 2019 at 10:02 AM Mariatta <mariatta at python.org> wrote:

> There was an error from Redis. I think this is the first time I've seen
> it, so I don't have any resolution on how to fix it right now.  ?
> I will look into handling the error and have miss-islington leave a
> comment in the PR when there is such error.
>
> log:
>
> at=info method=POST path="/" host=miss-islington.herokuapp.com request_id=8de611a2-6112-4039-a425-97850ac989b0 fwd="140.82.115.15" dyno=web.1 connect=1ms service=1005ms status=200 bytes=168 protocol=https
> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 600, in send_packed_command
> May 08 09:35:15 miss-islington app/web.1:     self._sock.sendall(item)
> May 08 09:35:15 miss-islington app/web.1: TimeoutError: [Errno 110] Connection timed out
> May 08 09:35:15 miss-islington app/web.1: During handling of the above exception, another exception occurred:
> May 08 09:35:15 miss-islington app/web.1: Traceback (most recent call last):
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
> May 08 09:35:15 miss-islington app/web.1:     yield
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/base.py", line 744, in send_task
> May 08 09:35:15 miss-islington app/web.1:     self.backend.on_task_call(P, task_id)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 265, in on_task_call
> May 08 09:35:15 miss-islington app/web.1:     self.result_consumer.consume_from(task_id)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 126, in consume_from
> May 08 09:35:15 miss-islington app/web.1:     self._consume_from(task_id)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/backends/redis.py", line 132, in _consume_from
> May 08 09:35:15 miss-islington app/web.1:     self._pubsub.subscribe(key)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3096, in subscribe
> May 08 09:35:15 miss-islington app/web.1:     ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3009, in execute_command
> May 08 09:35:15 miss-islington app/web.1:     self._execute(connection, connection.send_command, *args)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
> May 08 09:35:15 miss-islington app/web.1:     return command(*args)
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
> May 08 09:35:15 miss-islington app/web.1:     self.send_packed_command(self.pack_command(*args))
> May 08 09:35:15 miss-islington app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/redis/connection.py", line 613, in send_packed_command
> May 08 09:35:15 miss-islington app/web.1:     (errno, errmsg))
> May 08 09:35:15 miss-islington app/web.1: redis.exceptions.ConnectionError: Error 110 while writing to socket. Connection timed out.
>
>
>
> ?
>
> On Wed, May 8, 2019 at 9:44 AM Gregory P. Smith <greg at krypto.org> wrote:
>
>> Yesterday it failed to produce a backport or tell me that it couldn't
>> (after the "i'm now working on ..." message was left on the master PR).  I
>> waited a couple hours just in case and ran cherry_picker myself instead.
>> Same thing today apparently on
>> https://github.com/python/cpython/pull/13192 assuming the usual backport
>> latency is no more than a minute or two.
>>
>> -gps
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
>>
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190509/c7fa7e85/attachment.html>

From barry at python.org  Thu May  9 13:59:03 2019
From: barry at python.org (Barry Warsaw)
Date: Thu, 9 May 2019 13:59:03 -0400
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as core
 developers
Message-ID: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>

If you like the way mail.python.org and Mailman (both 2 and 3) Just Work, and are about as reliable as any service can be, we have our wonderful postmasters to thank.  Mark has been a postmaster for years and is currently maintaining GNU Mailman, both as a project and as a service on mpo.  Abhilash maintains the GNU Mailman 3 branch, has been project leader since I retired in that role back in 2017, and also maintains the Mailman 3 instance on mail.python.org.

More than that, because of their roles as Mailman developers, they have a deep knowledge of email in general, and in the email package in particular.  As I rarely dabble in the email package these days, and RDM --who did a fantastic job of implementing the new APIs and features in email for Python 3? has also scaled back his involvement, it means that the email package doesn?t get much attention these days.  Both Mark and Abhilash have an interest in helping to maintain the email package moving forward, and both are eminently qualified to do so.

I have worked with both of them for many many years, and I have the utmost respect for their technical and social skills, their understanding of Python processes, and their love of the Python language and community.  I've sprinted with them at many Pycons, until I scaled back my involvement with Mailman.  Both are here sprinting at Pycon 2019.

Therefore, with their permission, I propose extending core developer rights to both Mark and Abhilash.

As per PEP 13, I plan on opening a vote on Discourse next week (once I kind of recover from Pycon) for each developer.

Cheers,
-Barry


-------------- next part --------------
A non-text attachment was scrubbed...
Name: signature.asc
Type: application/pgp-signature
Size: 833 bytes
Desc: Message signed with OpenPGP
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190509/fd7e6298/attachment-0001.sig>

From andrew.svetlov at gmail.com  Thu May  9 15:14:06 2019
From: andrew.svetlov at gmail.com (Andrew Svetlov)
Date: Thu, 9 May 2019 15:14:06 -0400
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
Message-ID: <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>

A link to a list of CPython commits (Pull Requests) for both these
guys would be greatly appreciated.

On Thu, May 9, 2019 at 1:59 PM Barry Warsaw <barry at python.org> wrote:
>
> If you like the way mail.python.org and Mailman (both 2 and 3) Just Work, and are about as reliable as any service can be, we have our wonderful postmasters to thank.  Mark has been a postmaster for years and is currently maintaining GNU Mailman, both as a project and as a service on mpo.  Abhilash maintains the GNU Mailman 3 branch, has been project leader since I retired in that role back in 2017, and also maintains the Mailman 3 instance on mail.python.org.
>
> More than that, because of their roles as Mailman developers, they have a deep knowledge of email in general, and in the email package in particular.  As I rarely dabble in the email package these days, and RDM --who did a fantastic job of implementing the new APIs and features in email for Python 3? has also scaled back his involvement, it means that the email package doesn?t get much attention these days.  Both Mark and Abhilash have an interest in helping to maintain the email package moving forward, and both are eminently qualified to do so.
>
> I have worked with both of them for many many years, and I have the utmost respect for their technical and social skills, their understanding of Python processes, and their love of the Python language and community.  I've sprinted with them at many Pycons, until I scaled back my involvement with Mailman.  Both are here sprinting at Pycon 2019.
>
> Therefore, with their permission, I propose extending core developer rights to both Mark and Abhilash.
>
> As per PEP 13, I plan on opening a vote on Discourse next week (once I kind of recover from Pycon) for each developer.
>
> Cheers,
> -Barry
>
>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/



-- 
Thanks,
Andrew Svetlov

From antoine at python.org  Fri May 10 11:07:52 2019
From: antoine at python.org (Antoine Pitrou)
Date: Fri, 10 May 2019 17:07:52 +0200
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
 <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
Message-ID: <b1a27533-f59d-a64d-6b8f-3ab39d3d59e3@python.org>


I'd like to second Andrew's request.

Regards

Antoine.


Le 09/05/2019 ? 21:14, Andrew Svetlov a ?crit?:
> A link to a list of CPython commits (Pull Requests) for both these
> guys would be greatly appreciated.
> 
> On Thu, May 9, 2019 at 1:59 PM Barry Warsaw <barry at python.org> wrote:
>>
>> If you like the way mail.python.org and Mailman (both 2 and 3) Just Work, and are about as reliable as any service can be, we have our wonderful postmasters to thank.  Mark has been a postmaster for years and is currently maintaining GNU Mailman, both as a project and as a service on mpo.  Abhilash maintains the GNU Mailman 3 branch, has been project leader since I retired in that role back in 2017, and also maintains the Mailman 3 instance on mail.python.org.
>>
>> More than that, because of their roles as Mailman developers, they have a deep knowledge of email in general, and in the email package in particular.  As I rarely dabble in the email package these days, and RDM --who did a fantastic job of implementing the new APIs and features in email for Python 3? has also scaled back his involvement, it means that the email package doesn?t get much attention these days.  Both Mark and Abhilash have an interest in helping to maintain the email package moving forward, and both are eminently qualified to do so.
>>
>> I have worked with both of them for many many years, and I have the utmost respect for their technical and social skills, their understanding of Python processes, and their love of the Python language and community.  I've sprinted with them at many Pycons, until I scaled back my involvement with Mailman.  Both are here sprinting at Pycon 2019.
>>
>> Therefore, with their permission, I propose extending core developer rights to both Mark and Abhilash.
>>
>> As per PEP 13, I plan on opening a vote on Discourse next week (once I kind of recover from Pycon) for each developer.
>>
>> Cheers,
>> -Barry
>>
>>
>> _______________________________________________
>> python-committers mailing list
>> python-committers at python.org
>> https://mail.python.org/mailman/listinfo/python-committers
>> Code of Conduct: https://www.python.org/psf/codeofconduct/
> 
> 
> 

From vstinner at redhat.com  Mon May 13 04:14:07 2019
From: vstinner at redhat.com (Victor Stinner)
Date: Mon, 13 May 2019 10:14:07 +0200
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
 <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
Message-ID: <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>

Hi,

To be honest, my first reaction is the same than Andrew and Antoine: I
don't know these 2 contributors. I didn't see them around the bug
tracker, reviews, nor in commits.

The definition of what is a core developer is still a work-in-progress
:-) The PEP 13 tries to define it:

   https://www.python.org/dev/peps/pep-0013/#the-core-team

I'm no longer sure myself that I can define them. I prefer to repeat
what others say :-) Basically, a core developers is someone who
produces commits :-) That's one definition. Another one is someone who
a very good background to produce very good reviews and mentor
contributors. In which case can we put Mark Sapiro and Abhilash Raj?


Le jeu. 9 mai 2019 ? 21:14, Andrew Svetlov <andrew.svetlov at gmail.com> a ?crit :
> > If you like the way mail.python.org and Mailman (both 2 and 3) Just Work, and are about as reliable as any service can be, we have our wonderful postmasters to thank.  Mark has been a postmaster for years and is currently maintaining GNU Mailman, both as a project and as a service on mpo.  Abhilash maintains the GNU Mailman 3 branch, has been project leader since I retired in that role back in 2017, and also maintains the Mailman 3 instance on mail.python.org.

Having a sustainable Mailman project is great. But how does that
relate to Python itself? Are you talking about the email module? Do
Mark Sapiro and Abhilash Raj plan to maintain the email module?

I found "Mark Sapiro" mentioned in 4 commits (3 in 2013, 1 in 2006).

Abhilash Raj authored 1 commit in 2015 and 1 in 2014: both in the email module.

Sorry, I didn't dig into the bug tracker / GitHub to check if they are
active there.


> > More than that, because of their roles as Mailman developers, they have a deep knowledge of email in general, and in the email package in particular.  As I rarely dabble in the email package these days, and RDM --who did a fantastic job of implementing the new APIs and features in email for Python 3? has also scaled back his involvement, it means that the email package doesn?t get much attention these days.  Both Mark and Abhilash have an interest in helping to maintain the email package moving forward, and both are eminently qualified to do so.

I would prefer to first see them more involved upstream, before
starting to discuss promoting them. They are other contributors who
are way more active than them.

In the meanwhile, they don't have to be core devs to help to maintain
the email module, no?

I'm not sure about giving the core dev status as a recognizition for
their work on a different project. It sounds unfair to contributors
who are working on Python but are not core dev. There are other ways
to recognize valuable persons in the Python community, like the PSF
Community Awards and PSF Fellows.

Victor
-- 
Night gathers, and now my watch begins. It shall not end until my death.

From antoine at python.org  Mon May 13 05:38:33 2019
From: antoine at python.org (Antoine Pitrou)
Date: Mon, 13 May 2019 11:38:33 +0200
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
 <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
 <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>
Message-ID: <904bc5c7-851f-37a8-1048-c1c7775ed3c0@python.org>


Le 13/05/2019 ? 10:14, Victor Stinner a ?crit?:
> 
> I would prefer to first see them more involved upstream, before
> starting to discuss promoting them. They are other contributors who
> are way more active than them.
> 
> In the meanwhile, they don't have to be core devs to help to maintain
> the email module, no?
> 
> I'm not sure about giving the core dev status as a recognizition for
> their work on a different project. It sounds unfair to contributors
> who are working on Python but are not core dev. There are other ways
> to recognize valuable persons in the Python community, like the PSF
> Community Awards and PSF Fellows.

I'll also point out that giving core dev status to people who are active
on different projects but not CPython didn't lead to any significant
results in the past (I'm thinking about e.g. the Twisted core devs).

This is not a criticism about particular people, simply a reflection on
our own practice.  We should recognize that we don't attract active
contributors by giving them status upfront.

Regards

Antoine.

From barry at python.org  Mon May 13 19:11:06 2019
From: barry at python.org (Barry Warsaw)
Date: Mon, 13 May 2019 16:11:06 -0700
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
 <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
 <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>
Message-ID: <CABC2248-9BC8-4785-BD32-735D837A13B6@python.org>

On May 13, 2019, at 01:14, Victor Stinner <vstinner at redhat.com> wrote:

> I'm no longer sure myself that I can define them. I prefer to repeat
> what others say :-) Basically, a core developers is someone who
> produces commits :-) That's one definition.

But, IMHO not a correct one.  The full quote from PEP 13:

??snip snip??
Python core team members demonstrate:

? a good grasp of the philosophy of the Python Project
? a solid track record of being constructive and helpful
? significant contributions to the project's goals, in any form
? willingness to dedicate some time to improving Python

As the project matures, contributions go beyond code. Here's an incomplete list of areas where contributions may be considered for joining the core team, in no particular order:

? Working on community management and outreach
? Providing support on the mailing lists and on IRC
? Triaging tickets
? Writing patches (code, docs, or tests)
? Reviewing patches (code, docs, or tests)
? Participating in design decisions
? Providing expertise in a particular domain (security, i18n, etc.)
? Managing the continuous integration infrastructure
? Managing the servers (website, tracker, documentation, etc.)
? Maintaining related projects (alternative interpreters, core infrastructure like packaging, etc.)
? Creating visual designs

Core team membership acknowledges sustained and valuable efforts that align well with the philosophy and the goals of the Python project.
??snip snip??

I?m quite convinced that both Mark and Abhilash meet these requirements.  And they are almost by definition the experts in the email package.  You can certainly see the nature of their work in the Mailman repos, and I would be willing to mentor them through the first few commits to the CPython repo, though I think it will be mostly perfunctory.

> Having a sustainable Mailman project is great. But how does that
> relate to Python itself? Are you talking about the email module? Do
> Mark Sapiro and Abhilash Raj plan to maintain the email module?

Yes, that is the intent.

> In the meanwhile, they don't have to be core devs to help to maintain
> the email module, no?

Do we have any core developers who want to maintain it?  Not me :) and apparently not RDM.

-Barry

-------------- next part --------------
A non-text attachment was scrubbed...
Name: signature.asc
Type: application/pgp-signature
Size: 833 bytes
Desc: Message signed with OpenPGP
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190513/0f1e8b23/attachment.sig>

From greg at krypto.org  Mon May 13 19:19:50 2019
From: greg at krypto.org (Gregory P. Smith)
Date: Mon, 13 May 2019 16:19:50 -0700
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <CABC2248-9BC8-4785-BD32-735D837A13B6@python.org>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
 <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
 <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>
 <CABC2248-9BC8-4785-BD32-735D837A13B6@python.org>
Message-ID: <CAGE7PNKXJD-vWsAvgSihSBG3gEW5_7cKkXUeAfo=iR5iYzYm+A@mail.gmail.com>

On Mon, May 13, 2019 at 4:11 PM Barry Warsaw <barry at python.org> wrote:

> On May 13, 2019, at 01:14, Victor Stinner <vstinner at redhat.com> wrote:
>
> > I'm no longer sure myself that I can define them. I prefer to repeat
> > what others say :-) Basically, a core developers is someone who
> > produces commits :-) That's one definition.
>
> But, IMHO not a correct one.  The full quote from PEP 13:
>
> ??snip snip??
> Python core team members demonstrate:
>
> ? a good grasp of the philosophy of the Python Project
> ? a solid track record of being constructive and helpful
> ? significant contributions to the project's goals, in any form
> ? willingness to dedicate some time to improving Python
>
> As the project matures, contributions go beyond code. Here's an incomplete
> list of areas where contributions may be considered for joining the core
> team, in no particular order:
>
> ? Working on community management and outreach
> ? Providing support on the mailing lists and on IRC
> ? Triaging tickets
> ? Writing patches (code, docs, or tests)
> ? Reviewing patches (code, docs, or tests)
> ? Participating in design decisions
> ? Providing expertise in a particular domain (security, i18n, etc.)
> ? Managing the continuous integration infrastructure
> ? Managing the servers (website, tracker, documentation, etc.)
> ? Maintaining related projects (alternative interpreters, core
> infrastructure like packaging, etc.)
> ? Creating visual designs
>
> Core team membership acknowledges sustained and valuable efforts that
> align well with the philosophy and the goals of the Python project.
> ??snip snip??
>
> I?m quite convinced that both Mark and Abhilash meet these requirements.
> And they are almost by definition the experts in the email package.  You
> can certainly see the nature of their work in the Mailman repos, and I
> would be willing to mentor them through the first few commits to the
> CPython repo, though I think it will be mostly perfunctory.
>
> > Having a sustainable Mailman project is great. But how does that
> > relate to Python itself? Are you talking about the email module? Do
> > Mark Sapiro and Abhilash Raj plan to maintain the email module?
>
> Yes, that is the intent.
>
> > In the meanwhile, they don't have to be core devs to help to maintain
> > the email module, no?
>
> Do we have any core developers who want to maintain it?  Not me :) and
> apparently not RDM.
>

I think these two make sense as email module maintainers from a
demonstrated domain expertise point of view.

But you'll probably have an easier time convincing others who want to see
some PRs first if you just go ahead and have them do some work on the email
module in the form of PRs to start with.  ie: Don't let being dubbed core
developers or not yet block you from starting to mentor them on initial
email module maintenance.

-gps


> -Barry
>
> _______________________________________________
> python-committers mailing list
> python-committers at python.org
> https://mail.python.org/mailman/listinfo/python-committers
> Code of Conduct: https://www.python.org/psf/codeofconduct/
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://mail.python.org/pipermail/python-committers/attachments/20190513/3d69b294/attachment.html>

From tjreedy at udel.edu  Mon May 13 21:58:06 2019
From: tjreedy at udel.edu (Terry Reedy)
Date: Mon, 13 May 2019 21:58:06 -0400
Subject: [python-committers] Promote Mark Sapiro and Abhilash Raj as
 core developers
In-Reply-To: <CABC2248-9BC8-4785-BD32-735D837A13B6@python.org>
References: <D1DAFB0C-95E1-4BC2-9760-CE5DC3C24EE0@python.org>
 <CAL3CFcWvOW9oi-LD8WRRBL-yKyxcePci6KhyM61L9BTk4Z7dAw@mail.gmail.com>
 <CA+3bQGEAtg-MzUpzYZhqG=VF-oovP2TT3xgmUyTtGa7zSocokg@mail.gmail.com>
 <CABC2248-9BC8-4785-BD32-735D837A13B6@python.org>
Message-ID: <c28071a3-4c90-1088-f384-4604016e5b87@udel.edu>

On 5/13/2019 7:11 PM, Barry Warsaw wrote:
> On May 13, 2019, at 01:14, Victor Stinner <vstinner at redhat.com> wrote:
> 
>> I'm no longer sure myself that I can define them. I prefer to repeat
>> what others say :-) Basically, a core developers is someone who
>> produces commits :-) That's one definition.
> 
> But, IMHO not a correct one.

I think 'half complete' rather than 'not correct' is more accurate. 
There are two main effects of being granted 'core developer' status.

1. One may edit and merge PRs by onself or others into a python 
repository and in particular python/cypthon . This, expanded, is 
Victor's 'produce commits'.

2. One may participate in coredev-only discussions and votes.

These are the activities that differentiate of a 'core developer' and it 
is not wrong to say that a core developer is one who may do these.

>  The full quote from PEP 13:
> ??snip snip??
> Python core team members demonstrate:
> 
> ? a good grasp of the philosophy of the Python Project
> ? a solid track record of being constructive and helpful
> ? significant contributions to the project's goals, in any form
> ? willingness to dedicate some time to improving Python

This are qualities and history that once should have to become a core 
developer.  For producing commits, one should, in particular, understand 
the difference, as used here, between 'bug fix' and 'enhancement' and 
support the policy of not adding enhancements to x.y after x.y.0 (after 
.b1, actually).  (The devguide says something about this, but I don't 
know if it is clear enough.)

> As the project matures, contributions go beyond code. Here's an incomplete list of areas where contributions may be considered for joining the core team, in no particular order:

'may', not 'should' or 'must'.  Different existing coredevs may 
legitimately give these different weights.

> ? Working on community management and outreach
...
> ? Creating visual designs

Neither of these two speak to being qualified to produce commits.  Many 
of those I snipped do.

> Core team membership acknowledges sustained and valuable efforts that align well with the philosophy and the goals of the Python project.
> ??snip snip??

This sentence could be misinterpreted as saying that codedev status is 
an award for past contributions rather than an enabling greater future 
contributions.

Summarizing the general considerations, I have two questions for any 
candidate.

1. Do you want to become a core developer and do you intend to use the 
commit privilege?  If not, the question is not worth our time.

2. Do you understand our definition of 'bug fix' versus 'enhancement' 
and how and why the difference is important.  If not,
---

> I?m quite convinced that both Mark and Abhilash meet these requirements.  And they are almost by definition the experts in the email package.  You can certainly see the nature of their work in the Mailman repos, and I would be willing to mentor them through the first few commits to the CPython repo, though I think it will be mostly perfunctory.
> 
>> Having a sustainable Mailman project is great. But how does that
>> relate to Python itself? Are you talking about the email module? Do
>> Mark Sapiro and Abhilash Raj plan to maintain the email module?
> 
> Yes, that is the intent.
> 
>> In the meanwhile, they don't have to be core devs to help to maintain
>> the email module, no?
> 
> Do we have any core developers who want to maintain it?  Not me :) and apparently not RDM.

I searched the tracker for open issues with the email component marked. 
I was somewhat surprised to see 151, which is about the number for IDLE 
a few years ago.  We definitely need an active core developer working on 
email and team of two who can work together and check each other's work 
would be good.  (If and when we do, I can give suggestions, if asked, on 
managing such an intimidating pile.)

--
Terry


